### ISSUE TITLE
Add the ability to authenticate to GCP from a credentials file

### ISSUE THREAD

**Issue by hiddenillusion** [google/cloud-forensics-utils#247]
The method to authenticate to GCP is currently limited to using the Application Default Credentials -> [default](https://github.com/google/cloud-forensics-utils/blob/master/libcloudforensics/providers/gcp/internal/common.py#L128).

It would be useful if the option to obtain credentials from a credentials file also existed e.g. `providers/gcp/internal/common.py`:
```
from google.oauth2 import service_account
...
def CreateService(service_name: str,
                  key_file: Optional[str] = None,
                  api_version: str) -> 'googleapiclient.discovery.Resource':
...
credentials = service_account.Credentials.from_service_account_file(key_file)
```

**Comment by giovannt0** [comment]
Hi @hiddenillusion,

I'm looking into this issue right now. I think the behaviour of `default()` has changed since you reported this issue. Indeed, the documentation states:

```
If the environment variable ``GOOGLE_APPLICATION_CREDENTIALS`` is set to the path of a valid service account JSON private key file, then it is loaded and returned.
```

It is therefore supported, so long as `GOOGLE_APPLICATION_CREDENTIALS` is set. I'll go ahead and close this; feel free to re-open if it doesn't match what you were expecting.
